# Generated by Django 4.2.3 on 2023-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_autor', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('D', 'Drama'), ('S', 'Suspense'), ('R', 'Romance')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('editora', models.CharField(max_length=30)),
                ('autores', models.CharField(max_length=30)),
                ('publicacao_ano', models.DateField()),
            ],
        ),
    ]
