# Generated by Django 4.2.3 on 2023-07-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_data', '0002_rename_name_autor_autor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
