# Generated by Django 4.2.3 on 2023-08-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_data', '0005_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='genero',
            field=models.CharField(choices=[('D', 'Drama'), ('S', 'Suspense'), ('R', 'Romance'), ('F', 'Fantasia'), ('B', 'Biografia')], default='R', max_length=1),
        ),
    ]
